id: P009306
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25425
  title: འདབ་ཆགས་ཀྱི་ཞིང་ཁམས།
  author: ''
  volumes:
    8735932d013049749075880cd26c55ef:
      image_group_id: I1KG25427
      title: ''
      volume_number: 1
      total_pages: 180
